version: '2'
services:
  myredis:
    image: myredis:5.0
    ports:
      - "6379:6379"
  myeureka:
    image: myeureka:1.0
    ports:
      - "8600:8600"
  myservicehi:
    image: myservicehi:1.0
    ports:
      - "8763:8763"
    links:
        - myeureka:discovery
  mygatewayservice:
    image: mygatewayservice:1.0
    ports:
      - "9007:9007"
    links:
      - myeureka:discovery
      - myredis:myredis_url